spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  profiles:
    active: debug
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: resource
          uri: http://gw-oauth-resource:8080/res
          predicates:
            - Path=/res
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
#        - id: auth
#          uri: http://gw-oauth-auth:8080/auth
#          predicates:
#            - Path=/auth/**
#        - id: oauth2
#          uri: http://gw-oauth-auth:8080/oauth2
#          predicates:
#            - Path=/oauth2/**

  security:
    oauth2:

      client:
        registration:
          gateway:
            provider: auth-srv
            client-id: gateway
            client-secret: gw-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://172.10.16.1:8030/login/oauth2/code/gateway
            scope: read
        provider:
          auth-srv:
            authorization-uri: http://172.10.16.1:8040/oauth/authorize
            token-uri: http://gw-oauth-auth:8080/oauth/token
#            check-token-uri: http://gw-oauth-auth:8080/oauth/check_token
            user-info-uri: http://gw-oauth-auth:8080/userinfo
            user-name-attribute: sub
#            user-info-authentication-method: form
            jwk-set-uri: http://top-oauth-server:8090/token_keys

#      client:
#        registration:
#          gateway:
#            provider: uaa
#            client-id: gateway
#            client-secret: secret
#            authorization-grant-type: authorization_code
#            redirect-uri: http://172.10.16.1:8030/login/oauth2/code/gateway
#            scope: openid,profile,email,resource.read
#        provider:
#          uaa:
#            authorization-uri: http://172.10.16.1:8090/uaa/oauth/authorize
#            token-uri: http://gw-oauth-uaa:8090/uaa/oauth/token
#            user-info-uri: http://gw-oauth-uaa:8090/uaa/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: http://gw-oauth-uaa:8090/uaa/token_keys

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE

server:
  port: 8030